name: Update lambda

on:
  push:
    branches:
      - main

jobs:
  update_lambda:
    name: 'Pull code & update lambda'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip lambda.zip file.txt
      - uses: stcalica/update-lambda
        with:
          package: lambda.zip
          function-name: email-me-lambda
          AWS_REGION: eu-west-1
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
